# Development Docker Compose Override
# Usage: docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up

version: '3.8'

services:
  # Override backend for development
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
      target: build
    environment:
      NODE_ENV: development
    volumes:
      - ./packages/backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    
  # Override frontend for development  
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      target: build
    environment:
      VITE_API_URL: http://localhost:3001/api
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

  # Add development database with seeded data
  db:
    environment:
      POSTGRES_DB: tourist_village_dev_db
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
    driver: local
    name: tourist-village-postgres-dev-data
